<?php
define('DOMAIN_SITE','//www.esrapi.com');
 define('SITE_NAME','ESRAPI');
 define('SITE_BRAND_IMG','icon-pepiuox.png');
 define('SITE_PATH','//localhost:130/');
 define('SITE_DESCRIPTION','Your description for your domains');
 define('SITE_KEYWORDS','Your keywords for your domains');
 define('SITE_CLASSIFICATION','Your classification for your domains');
 define('SITE_EMAIL','info@phpgrapesjs.com');
 define('SITE_IMAGE','dashboard');
 define('SITE_ADMIN','dashboard');
 define('SITE_CONTROL','users');
 define('SITE_CONFIG','siteconf');
 define('SITE_LANGUAGE_1','English');
 define('SITE_LANGUAGE_2','Spanish');
 define('FOLDER_IMAGES','uploads');
 define('SITE_CREATOR','admin');
 define('SITE_EDITOR','admin, editor');
 define('SITE_BUILDER','builder');
 define('SITE_LIST','list');
 define('NAME_CONTACT','Jose Mantilla');
 define('PHONE_CONTACT','0051999063645');
 define('EMAIL_CONTACT','contact@pepiuox.net');
 define('ADDRESS','Lima - Peru');
 define('TWITTER','@pepiuox');
 define('FACEBOOKID','pepiuox30675');
 define('SKYPE','pepiuox');
 define('TELEGRAM','pepiuox');
 define('WHATSAPP','+51 999063645');
 define('created','2022-01-08 08:42:41');
 define('updated','2023-12-22 23:33:14');
define('MAILSERVER','smtp.hostinger.com');
 define('PORTSERVER','461');
 define('USEREMAIL','YWlsMldhQ3E0UEtGbjhQTGQ4YUVPbUFvQjI4ZWxsNXEycjdVbXFSNG5MZz0=');
 define('PASSMAIL','bnVEa3VFZXV6eERRNjVDcEVpZWJNWEoxVW9WTEE1YTBmMnczTXB4aElFMD0=');
 define('SUPERADMIN_NAME','Super Admin');
 define('SUPERADMIN_LEVEL','9');
 define('ADMIN_NAME','Admin');
 define('ADMIN_LEVEL','5');
 define('SECURE_HASH','b5771f3c6b6f65fd39b059d34d294116ab321bc88abe2c6411036654d9c6a50d');
 define('SECURE_TOKEN','o]ZmhBH8g{#qmt4ndEAe[[$}[EcszyYYkX25E&db0Bz&E4e&]R2S5$AVb{%PyB{vxmVb$FM4d4wtw]3Prd((wnDzZaG7}{gCqLko$z#y5mj(wX({IRgu&Dd@xvd1wxwf');?>
