<?php
define('DOMAIN_SITE','//www.esrapi.com');
 define('SITE_NAME','ESRAPI');
 define('SITE_BRAND_IMG','icon-pepiuox.png');
 define('SITE_PATH','http://localhost:180/');
 define('SITE_DESCRIPTION','Your description for your domains');
 define('SITE_KEYWORDS','Your keywords for your domains');
 define('SITE_CLASSIFICATION','Your classification for your domains');
 define('SITE_EMAIL','contact@pepiuox.net');
 define('SITE_IMAGE','dashboard');
 define('SITE_ADMIN','dashboard');
 define('SITE_CONTROL','users');
 define('SITE_CONFIG','siteconf');
 define('SITE_LANGUAGE_1','English');
 define('SITE_LANGUAGE_2','Spanish');
 define('FOLDER_IMAGES','uploads');
 define('SITE_CREATOR','admin');
 define('SITE_EDITOR','admin, editor');
 define('SITE_BUILDER','builder');
 define('SITE_LIST','list');
 define('NAME_CONTACT','Jose Mantilla');
 define('PHONE_CONTACT','0051999063645');
 define('EMAIL_CONTACT','contact@pepiuox.net');
 define('ADDRESS','Lima - Peru');
 define('TWITTER','@pepiuox');
 define('FACEBOOKID','pepiuox30675');
 define('SKYPE','pepiuox');
 define('TELEGRAM','pepiuox');
 define('WHATSAPP','+51 999063645');
 define('created','2022-01-08 08:42:41');
 define('updated','2024-04-14 02:19:34');
define('MAILSERVER','smtp.hostinger.com');
 define('PORTSERVER','461');
 define('USEREMAIL','YWlsMldhQ3E0UEtGbjhQTGQ4YUVPbUFvQjI4ZWxsNXEycjdVbXFSNG5MZz0=');
 define('PASSMAIL','bnVEa3VFZXV6eERRNjVDcEVpZWJNWEoxVW9WTEE1YTBmMnczTXB4aElFMD0=');
 define('SUPERADMIN_NAME','Super Admin');
 define('SUPERADMIN_LEVEL','9');
 define('ADMIN_NAME','Admin');
 define('ADMIN_LEVEL','5');
 define('SECURE_HASH','e38ea8bcfb3a569a9461246217027a5e1a67e5fc2e9dbebba2f3f45520307f35');
 define('SECURE_TOKEN','cd34Mzh%%3aB]z]cP)nLG&]y9b2x[PFHvBwhOt2DsnNr#dDm32PZ$KDVyrTp#&)4V5udB]ql#hJ$Yss#i$c4S6psFBq$3RnnjQ0{9dhHUV)5YoPGJ)StMkaYPE7u696j');?>
