<?php
define('DOMAIN_SITE','http://www.pepiuox.net');
 define('SITE_NAME','PEPIUOX');
 define('SITE_BRAND_IMG','icon-pepiuox.png');
 define('SITE_PATH','http://localhost:130/');
 define('SITE_DESCRIPTION','Your description for your domains');
 define('SITE_KEYWORDS','Your keywords for your domains');
 define('SITE_CLASSIFICATION','Your classification for your domains');
 define('SITE_EMAIL','info@phpgrapesjs.com');
 define('SITE_IMAGE','dashboard');
 define('SITE_ADMIN','dashboard');
 define('SITE_CONTROL','users');
 define('SITE_CONFIG','siteconf');
 define('SITE_LANGUAGE_1','English');
 define('SITE_LANGUAGE_2','Spanish');
 define('FOLDER_IMAGES','uploads');
 define('SITE_CREATOR','admin');
 define('SITE_EDITOR','admin, editor');
 define('SITE_BUILDER','builder');
 define('SITE_LIST','list');
 define('NAME_CONTACT','Jose Mantilla');
 define('PHONE_CONTACT','0051999063645');
 define('EMAIL_CONTACT','contact@pepiuox.net');
 define('ADDRESS','Lima - Peru');
 define('TWITTER','@pepiuox');
 define('FACEBOOKID','pepiuox30675');
 define('SKYPE','pepiuox');
 define('TELEGRAM','pepiuox');
 define('WHATSAPP','+51 999063645');
 define('MAILSERVER','smtp.hostinger.com');
 define('PORTSERVER','461');
 define('USEREMAIL','contact@pepiuox.net');
 define('PASSMAIL','truelove');
 define('SUPERADMIN_NAME','Super Admin');
 define('SUPERADMIN_LEVEL','9');
 define('ADMIN_NAME','Admin');
 define('ADMIN_LEVEL','5');
 define('SECURE_HASH','6be6501413cbf5e9e69c9db0b5f432d635d5d49db7d7505596bef4e902f9605c');
 define('SECURE_TOKEN',')H7Q&C[zSQ[P0HZTNdQyR25P9pRKo5iXs$3Y86zN8cIZQpoUlK4RDQAkLLD2h7cRQ3&d)[Js7M)OInozQeICXa{(7&6K2sj%ziCYeAoKON)5p(1n5OK%1D2vexjl{JO6');?>
