<?php
define('DOMAIN_SITE','http://www.pepiuox.net');
 define('SITE_NAME','PEPIUOX');
 define('SITE_BRAND_IMG','icon-pepiuox.png');
 define('SITE_PATH','http://localhost:130/');
 define('SITE_DESCRIPTION','Your description for your domains');
 define('SITE_KEYWORDS','Your keywords for your domains');
 define('SITE_CLASSIFICATION','Your classification for your domains');
 define('SITE_EMAIL','info@phpgrapesjs.com');
 define('SITE_IMAGE','dashboard');
 define('SITE_ADMIN','dashboard');
 define('SITE_CONTROL','users');
 define('SITE_CONFIG','siteconf');
 define('SITE_LANGUAGE_1','English');
 define('SITE_LANGUAGE_2','Spanish');
 define('FOLDER_IMAGES','uploads');
 define('SITE_CREATOR','admin');
 define('SITE_EDITOR','admin, editor');
 define('SITE_BUILDER','builder');
 define('SITE_LIST','list');
 define('NAME_CONTACT','Jose Mantilla');
 define('PHONE_CONTACT','0051999063645');
 define('EMAIL_CONTACT','contact@pepiuox.net');
 define('ADDRESS','Lima - Peru');
 define('TWITTER','@pepiuox');
 define('FACEBOOKID','pepiuox30675');
 define('SKYPE','pepiuox');
 define('TELEGRAM','pepiuox');
 define('WHATSAPP','+51 999063645');
 define('MAILSERVER','smtp.hostinger.com');
 define('PORTSERVER','461');
 define('USEREMAIL','contact@pepiuox.net');
 define('PASSMAIL','truelove');
 define('SUPERADMIN_NAME','Super Admin');
 define('SUPERADMIN_LEVEL','9');
 define('ADMIN_NAME','Admin');
 define('ADMIN_LEVEL','5');
 define('SECURE_HASH','d4d6234d6e90b6d34877630d6ff640c1b0a62751a900a20d36337dc6bfef0aaa');
 define('SECURE_TOKEN','HjB1TAMLii4eQl3(8}8%P2shg)D([yshop)gX[##0GkV]51NUI3&AMwqGcnL)JtUk]@lO7g1h#HFOqAAQuk61lDO9umL1w88hCSA]I5EKT2)ZwQTMoIIP9[IrCUJqdtN');?>
