<?php
define('DOMAIN_SITE','http://www.pepiuox.net');
 define('SITE_NAME','PEPIUOX');
 define('SITE_BRAND_IMG','icon-pepiuox.png');
 define('SITE_PATH','http://localhost:130/');
 define('SITE_DESCRIPTION','Your description for your domains');
 define('SITE_KEYWORDS','Your keywords for your domains');
 define('SITE_CLASSIFICATION','Your classification for your domains');
 define('SITE_EMAIL','info@phpgrapesjs.com');
 define('SITE_IMAGE','dashboard');
 define('SITE_ADMIN','dashboard');
 define('SITE_CONTROL','users');
 define('SITE_CONFIG','siteconf');
 define('SITE_LANGUAGE_1','English');
 define('SITE_LANGUAGE_2','Spanish');
 define('FOLDER_IMAGES','uploads');
 define('SITE_CREATOR','admin');
 define('SITE_EDITOR','admin, editor');
 define('SITE_BUILDER','builder');
 define('SITE_LIST','list');
 define('NAME_CONTACT','Jose Mantilla');
 define('PHONE_CONTACT','0051999063645');
 define('EMAIL_CONTACT','contact@pepiuox.net');
 define('ADDRESS','Lima - Peru');
 define('TWITTER','@pepiuox');
 define('FACEBOOKID','pepiuox30675');
 define('SKYPE','pepiuox');
 define('TELEGRAM','pepiuox');
 define('WHATSAPP','+51 999063645');
 define('MAILSERVER','smtp.hostinger.com');
 define('PORTSERVER','461');
 define('USEREMAIL','contact@pepiuox.net');
 define('PASSMAIL','truelove');
 define('SUPERADMIN_NAME','Super Admin');
 define('SUPERADMIN_LEVEL','9');
 define('ADMIN_NAME','Admin');
 define('ADMIN_LEVEL','5');
 define('SECURE_HASH','d03ba90951cb364f60e89a82ba989172ced435d6365a199d1ef210c6d4e5f3fe');
 define('SECURE_TOKEN','V{l{lf)WCdLwau#EQbYNB}93oW78ExU{lzAQ4%ODev4w&RJdDdNvve4819BJcU]M&JrTkL8wAb6T&gEe2}vQ(9}6@r5BfkIpRR2Nad0ViRwSkeg5ouO4atdS$DEkAPQC');?>
