<?php
if(isset($_POST['addrow'])){
$DOMAIN_SITE = $_POST['DOMAIN_SITE'];
 $SITE_NAME = $_POST['SITE_NAME'];
 $SITE_BRAND_IMG = $_POST['SITE_BRAND_IMG'];
 $SITE_DESCRIPTION = $_POST['SITE_DESCRIPTION'];
 $SITE_KEYWORDS = $_POST['SITE_KEYWORDS'];
 $SITE_CLASSIFICATION = $_POST['SITE_CLASSIFICATION'];
 $SITE_EMAIL = $_POST['SITE_EMAIL'];
 $SITE_IMAGE = $_POST['SITE_IMAGE'];
 $SITE_ADMIN = $_POST['SITE_ADMIN'];
 $SITE_CONTROL = $_POST['SITE_CONTROL'];
 $SITE_CONFIG = $_POST['SITE_CONFIG'];
 $SITE_LANGUAGE_1 = $_POST['SITE_LANGUAGE_1'];
 $SITE_LANGUAGE_2 = $_POST['SITE_LANGUAGE_2'];
 $FOLDER_IMAGES = $_POST['FOLDER_IMAGES'];
 $SITE_CREATOR = $_POST['SITE_CREATOR'];
 $SITE_EDITOR = $_POST['SITE_EDITOR'];
 $SITE_BUILDER = $_POST['SITE_BUILDER'];
 $SITE_LIST = $_POST['SITE_LIST'];
 $NAME_CONTACT = $_POST['NAME_CONTACT'];
 $PHONE_CONTACT = $_POST['PHONE_CONTACT'];
 $EMAIL_CONTACT = $_POST['EMAIL_CONTACT'];
 $ADDRESS = $_POST['ADDRESS'];
 $TWITTER = $_POST['TWITTER'];
 $FACEBOOKID = $_POST['FACEBOOKID'];
 $SKYPE = $_POST['SKYPE'];
 $TELEGRAM = $_POST['TELEGRAM'];
 $WHATSAPP = $_POST['WHATSAPP'];
 $SUPERADMIN_NAME = $_POST['SUPERADMIN_NAME'];
 $SUPERADMIN_LEVEL = $_POST['SUPERADMIN_LEVEL'];
 $ADMIN_NAME = $_POST['ADMIN_NAME'];
 $ADMIN_LEVEL = $_POST['ADMIN_LEVEL'];
 $SECURE_HASH = $_POST['SECURE_HASH'];
 $SECURE_TOKEN = $_POST['SECURE_TOKEN'];
 $CREATE = $_POST['CREATE'];
 $UPDATED = $_POST['UPDATED'];

$sql = "INSERT INTO site_configuration (DOMAIN_SITE, SITE_NAME, SITE_BRAND_IMG, SITE_DESCRIPTION, SITE_KEYWORDS, SITE_CLASSIFICATION, SITE_EMAIL, SITE_IMAGE, SITE_ADMIN, SITE_CONTROL, SITE_CONFIG, SITE_LANGUAGE_1, SITE_LANGUAGE_2, FOLDER_IMAGES, SITE_CREATOR, SITE_EDITOR, SITE_BUILDER, SITE_LIST, NAME_CONTACT, PHONE_CONTACT, EMAIL_CONTACT, ADDRESS, TWITTER, FACEBOOKID, SKYPE, TELEGRAM, WHATSAPP, SUPERADMIN_NAME, SUPERADMIN_LEVEL, ADMIN_NAME, ADMIN_LEVEL, SECURE_HASH, SECURE_TOKEN, CREATE, UPDATED)
VALUES ('$DOMAIN_SITE', '$SITE_NAME', '$SITE_BRAND_IMG', '$SITE_DESCRIPTION', '$SITE_KEYWORDS', '$SITE_CLASSIFICATION', '$SITE_EMAIL', '$SITE_IMAGE', '$SITE_ADMIN', '$SITE_CONTROL', '$SITE_CONFIG', '$SITE_LANGUAGE_1', '$SITE_LANGUAGE_2', '$FOLDER_IMAGES', '$SITE_CREATOR', '$SITE_EDITOR', '$SITE_BUILDER', '$SITE_LIST', '$NAME_CONTACT', '$PHONE_CONTACT', '$EMAIL_CONTACT', '$ADDRESS', '$TWITTER', '$FACEBOOKID', '$SKYPE', '$TELEGRAM', '$WHATSAPP', '$SUPERADMIN_NAME', '$SUPERADMIN_LEVEL', '$ADMIN_NAME', '$ADMIN_LEVEL', '$SECURE_HASH', '$SECURE_TOKEN', '$CREATE', '$UPDATED')";
if ($this->connection->query($sql) === TRUE) {
    $_SESSION['success'] = 'The data was added correctly';
header('Location: dashboard.php?cms=crud&w=list&tbl=site_configuration');
} else {
    $_SESSION['error'] = 'Error: ' . $this->connection->error;
}

$this->connection->close();
}?> 
