<?php

//This is temporal file only for add new row
if (isset($_POST["updatequeries"])) {
    $granja_id = $_POST['granja_id'];
    $sql0 = "UPDATE table_queries SET query='$granja_id' WHERE tque_Id='62' ";
    $conn->query($sql0);
    $nombre = $_POST['nombre'];
    $sql1 = "UPDATE table_queries SET query='$nombre' WHERE tque_Id='63' ";
    $conn->query($sql1);
    $apellido_paterno = $_POST['apellido_paterno'];
    $sql2 = "UPDATE table_queries SET query='$apellido_paterno' WHERE tque_Id='64' ";
    $conn->query($sql2);
    $apellido_materno = $_POST['apellido_materno'];
    $sql3 = "UPDATE table_queries SET query='$apellido_materno' WHERE tque_Id='65' ";
    $conn->query($sql3);
    $genero = $_POST['genero'];
    $sql4 = "UPDATE table_queries SET query='$genero' WHERE tque_Id='66' ";
    $conn->query($sql4);
    $edad = $_POST['edad'];
    $sql5 = "UPDATE table_queries SET query='$edad' WHERE tque_Id='67' ";
    $conn->query($sql5);
    $cumpleanos = $_POST['cumpleanos'];
    $sql6 = "UPDATE table_queries SET query='$cumpleanos' WHERE tque_Id='68' ";
    $conn->query($sql6);
    $documento = $_POST['documento'];
    $sql7 = "UPDATE table_queries SET query='$documento' WHERE tque_Id='69' ";
    $conn->query($sql7);
    $numero_documento = $_POST['numero_documento'];
    $sql8 = "UPDATE table_queries SET query='$numero_documento' WHERE tque_Id='70' ";
    $conn->query($sql8);
    $imagen = $_POST['imagen'];
    $sql9 = "UPDATE table_queries SET query='$imagen' WHERE tque_Id='71' ";
    $conn->query($sql9);
    $telefono_celular = $_POST['telefono_celular'];
    $sql10 = "UPDATE table_queries SET query='$telefono_celular' WHERE tque_Id='72' ";
    $conn->query($sql10);
    $telefono_fijo = $_POST['telefono_fijo'];
    $sql11 = "UPDATE table_queries SET query='$telefono_fijo' WHERE tque_Id='73' ";
    $conn->query($sql11);
    $correo_electronico = $_POST['correo_electronico'];
    $sql12 = "UPDATE table_queries SET query='$correo_electronico' WHERE tque_Id='74' ";
    $conn->query($sql12);
    $fecha_ingreso = $_POST['fecha_ingreso'];
    $sql13 = "UPDATE table_queries SET query='$fecha_ingreso' WHERE tque_Id='75' ";
    $conn->query($sql13);
    $tipo_pago = $_POST['tipo_pago'];
    $sql14 = "UPDATE table_queries SET query='$tipo_pago' WHERE tque_Id='76' ";
    $conn->query($sql14);
    $tipo_financiera_id = $_POST['tipo_financiera_id'];
    $sql15 = "UPDATE table_queries SET query='$tipo_financiera_id' WHERE tque_Id='77' ";
    $conn->query($sql15);
    $banco_financiera_id = $_POST['banco_financiera_id'];
    $sql16 = "UPDATE table_queries SET query='$banco_financiera_id' WHERE tque_Id='78' ";
    $conn->query($sql16);
    $numero_cuenta = $_POST['numero_cuenta'];
    $sql17 = "UPDATE table_queries SET query='$numero_cuenta' WHERE tque_Id='79' ";
    $conn->query($sql17);
    $otra_cuenta = $_POST['otra_cuenta'];
    $sql18 = "UPDATE table_queries SET query='$otra_cuenta' WHERE tque_Id='80' ";
    $conn->query($sql18);
    $cargo_id = $_POST['cargo_id'];
    $sql19 = "UPDATE table_queries SET query='$cargo_id' WHERE tque_Id='81' ";
    $conn->query($sql19);
    $estado_laboral = $_POST['estado_laboral'];
    $sql20 = "UPDATE table_queries SET query='$estado_laboral' WHERE tque_Id='82' ";
    $conn->query($sql20);
    $salario = $_POST['salario'];
    $sql21 = "UPDATE table_queries SET query='$salario' WHERE tque_Id='83' ";
    $conn->query($sql21);
    $estado = $_POST['estado'];
    $sql22 = "UPDATE table_queries SET query='$estado' WHERE tque_Id='84' ";
    $conn->query($sql22);
    $creado = $_POST['creado'];
    $sql23 = "UPDATE table_queries SET query='$creado' WHERE tque_Id='85' ";
    $conn->query($sql23);
    echo "Record added successfully";
    header("Location: querybuilder.php?w=editor&tbl=personal");
}
?> 
